name: Hello World CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        run: echo "Setting up Python"
      - name: Install dependencies
        run: echo "Installing dependencies"
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: echo "Deploying application"
